server:
  port: 7979

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route:
      path: /user/**
      sensitiveHeaders:
      #      strip-prefix: false
      service-id: shopmall-cloud-provider-user
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000

