server:
  port: 8000

spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mallcloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    
security:
  oauth2:
    client:
      clientId: shopmall-client-user
      clientSecret: shopmallClientSecret
      access-token-uri: http://127.0.0.1:8000/oauth/token
      user-authorization-uri: http://127.0.0.1:8000/oauth/authorize
    resource:
      id: shopmall-resource-user
      filter-order: 3



shopmall:
  enableSqlLogInterceptor: false
  token:
    interceptor:
      enable: true
  oauth2:
    jwtSigningKey: shopmall
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header  
    oauth2:
      tokenStore: jwt
      clients[0]:
        clientId: shopmall-client-user
        clientSecret: shopmallClientSecret
        accessTokenValidateSeconds: 7200
        scope: "*"    
